// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// // ...
 
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm4uikCxygvguZyKbx-ItYqykbCxiqwt4',
    appId: '1:6705375096:web:e2518571969fb8c4640a8d',
    messagingSenderId: '6705375096',
    projectId: 'pencatatan-keuangan-7cb6d',
    authDomain: 'pencatatan-keuangan-7cb6d.firebaseapp.com',
    storageBucket: 'pencatatan-keuangan-7cb6d.appspot.com',
    measurementId: 'G-QKZLTFQDHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI_swE2lkOcFUJ153BHvk82x1MKp42jy0',
    appId: '1:6705375096:android:2c8cb918545c5eb0640a8d',
    messagingSenderId: '6705375096',
    projectId: 'pencatatan-keuangan-7cb6d',
    storageBucket: 'pencatatan-keuangan-7cb6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgzoNHTPFqIhGkP82tY09byIHMr3bmFJ0',
    appId: '1:6705375096:ios:2c84c937899791d1640a8d',
    messagingSenderId: '6705375096',
    projectId: 'pencatatan-keuangan-7cb6d',
    storageBucket: 'pencatatan-keuangan-7cb6d.appspot.com',
    iosBundleId: 'com.example.aplikasiPencatatanKeuangan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgzoNHTPFqIhGkP82tY09byIHMr3bmFJ0',
    appId: '1:6705375096:ios:2c84c937899791d1640a8d',
    messagingSenderId: '6705375096',
    projectId: 'pencatatan-keuangan-7cb6d',
    storageBucket: 'pencatatan-keuangan-7cb6d.appspot.com',
    iosBundleId: 'com.example.aplikasiPencatatanKeuangan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm4uikCxygvguZyKbx-ItYqykbCxiqwt4',
    appId: '1:6705375096:web:55e46202e2bce287640a8d',
    messagingSenderId: '6705375096',
    projectId: 'pencatatan-keuangan-7cb6d',
    authDomain: 'pencatatan-keuangan-7cb6d.firebaseapp.com',
    storageBucket: 'pencatatan-keuangan-7cb6d.appspot.com',
    measurementId: 'G-MSZWL5KYKV',
  );
}
